name: Build macOS .app

on:
  push:
    branches:
      - master
      - develop
      - feature/qt

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build the .app bundle
        run: |
          pyinstaller --name PDFMerger pyqt_app.py
          ls -l dist

      - name: Upload the built .app
        uses: actions/upload-artifact@v4
        with:
          name: PDFMerger
          path: dist/PDFMerger.app
